name: GitHubActions Demo
on: workflow_dispatch
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Buliding the code
          run: echo "code is bulid"
    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: test phase
          run: echo "running the code"
    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: deploy stage
          run: echo "deploting the code"
    
            
             
         
