name: GitHubActions Demo
on: push
jobs:
    bulid:
      runs-on: ubuntu-latest
      steps:
        - name: Hello
          run: |
              echo "adding line one"
              echo "adding second line"
              echo "third line is also added"
