name: GitHub Actions Demo
on: push
jobs:
    action-demo:
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
          uses: action/checkout@v6
        - name: print the index.html file
          run: cat index.html
    
            
             
         
