name: GitHubActions Demo
on: workflow_dispatch
jobs:
    bulid:
      runs-on: ubuntu-latest
      steps:
        - name: Buliding the code
          run: echo "code is bulid"
    Test:
      runs-on: ubuntu-latest
      steps:
        - name: test phase
          run: echo "running the code"
    Deploy:
        runs-on: ubuntu-latest
        steps:
          - name: deploy stage
            run: echo "deploting the code"
    
            
             
         
