name: input demo
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: Choose the env
        required: true
        default: dev
        options:
          - dev
          - test
          - prod
          - preprod
      artifact_tag: 
        description: Choose the artifact
        required: true
  jobs:
    inputs-demo:
      runs-on: ubuntu-latest
      steps:
        - name: deploy the app
          run: Deploy the ${{ inputs.artifact_tag }} on the env ${{ inputs.environment }}
      
  
