name: outputs demo
on: push
jobs:
  build:
   outputs:
     version: ${{ steps.Step1.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        id: Step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy the code
        run: echo "deploy the version ${{ needs.build.outputs.version }}"
