name: outputs demo
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        id: Step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
      - name: step two
        run: echo "This is version ${{ steps.Step1.outputs.version }}"
